### PR TITLE
week_3

### PR DESCRIPTION
**Pull request by LinVince**
林岳瑾
http://54.168.160.56:3000/
http://54.168.160.56:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done but size and color of radio buttons are incorrect.

**Review by LinVince — COMMENTED** [review]
I've changed the color and the size of the radio button

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by LinVince** [comment]
Thanks

**Pull request merged**
