### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by LinVince**
林岳瑾
http://54.168.160.56:3000/
http://54.168.160.56:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. We don't need to use setTimeout after signing in, it's too long to wait.
2. Add link to home page on your website title.

**Comment by LinVince** [comment]
Thanks! I've made required changes.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Alignment of your sign in/up text in attraction page is broken.
2. I cannot close your dialog after opening, there should have a close icon inside based on our design.
54 168 160 56_3000_attraction_4

**Comment by LinVince** [comment]
Omg! I'm so careless..... I've fixed everything and added the close button.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
